# Generated by Django 2.2.24 on 2023-03-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20190829_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Новостройка ли'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активно-ли объявление'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='has_balcony',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Наличие балкона'),
        ),
    ]
