# Generated by Django 2.2.24 on 2023-03-24 09:11

from django.db import migrations
import phonenumbers


def set_normalize_phonenumber(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.owners_phonenumber:
            flat.owner_pure_phone = phonenumbers.format_number(phonenumbers.parse(flat.owners_phonenumber, "RU"),
                                                               phonenumbers.PhoneNumberFormat.E164)
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20230324_1028'),
    ]

    operations = [
        migrations.RunPython(set_normalize_phonenumber, move_backward),
    ]
