# Generated by Django 2.2.24 on 2023-03-24 09:11

from django.db import migrations
import phonenumbers


def set_normalize_phonenumber(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        owner_pure_phone = phonenumbers.parse(flat.owners_phonenumber, "RU")
        if phonenumbers.is_valid_number(owner_pure_phone):
            flat.owner_pure_phone = phonenumbers.format_number(owner_pure_phone, phonenumbers.PhoneNumberFormat.E164)
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(set_normalize_phonenumber),
    ]
