# Generated by Django 2.2.24 on 2023-03-25 16:04

from django.db import migrations


def link_owners_and_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        owner.flat.set(Flat.objects.filter(owner=owner.owner, owner_pure_phone=owner.owner_pure_phone))
        owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20230326_1516'),
    ]

    operations = [
        migrations.RunPython(link_owners_and_flats),
    ]
